server {
    listen 8080;
    host 127.0.0.1;
    server_name localhost;
    root ./www;

    location / {
        methods GET;
        index index.html;
    }

    location /images {
        methods GET;
        root ./www/images;
        autoindex on;
    }

    location /upload {
        methods GET POST;
        root ./www/upload;
        index upload.html;
    }

    location /delete {
        methods GET DELETE;
        root ./www/files;
    }

    location /no-delete {
        methods GET POST;
        root ./www/files;
    }
}