server {
    listen 8080;
    host localhost;
    root ./test;
    index index.html;

    location / {
        root ./test;
        methods GET POST;
        index index.html;
        # client_max_body_size 10;
		upload_dir test/upload;
    }
}
