server {
    listen 8080;
    host localhost;
    root ./test;
    index index.html;

    location / {
        root ./test;
        auto_index true;
        methods GET POST;
    }

    location /cgi-bin {
        root ./test;
        auto_index true;
        methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}
