server {
    listen 8080;
    host localhost;
    root /tmp/webserv_mock;
    index index.html;

    location / {
        root /tmp/webserv_mock;
        methods GET POST DELETE;
    }

    location /api/ {
        root /tmp/webserv_mock;
        methods GET POST DELETE;
    }
}
