server {
    listen 8080;
    host localhost;
    root ./test;
    index index.html;
	error_page 404 test/404.html;

    location / {
        root ./test;
        methods GET POST DELETE;
        index tester.html;
		upload_dir test/upload;
		auto_index true;
    }

}


server {
    listen 8081;
    host localhost;
    root ./test;
    index index.html;
	error_page 404 test/404.html;

    location / {
        root ./test;
        methods GET POST DELETE;
        index tester.html;
		upload_dir test/upload;
		auto_index true;
    }

}
