server {
    listen 8080;
    host localhost;
    root .;
    index Makefile;

	location /old/ {
		return 301 http://localhost:8080/;
	}

    location / {
        root .;
        methods GET;
    }
}


