server {
    listen 8080;
    host localhost;
    root ./test;
    index index.html;
	error_page 404 test/404.html;

    location / {
        root ./test;
        methods GET  ;
        index index.html;
		upload_dir test/upload;
		auto_index true;
    }

    location /cgi-bin {
		return 301 http://localhost:8080/;
    }
}
