server {
    listen 8080;
    host 127.0.0.1;
    server_name localhost;
    root ./test;

    location / {
        methods GET;
        index tester.html;
    }


    location /uploads {
        methods GET POST;
        root ./test;
        index upload.html;
        upload_dir ./test/uploads;
        # client_max_body_size 30;
    }

}