server {
    listen 8080;
    host localhost;
    root ./test;
    index index.html;
	error_page 404 test/404.html;

    location / {
        root ./test;
        methods GET POST DELETE;
        index tester.html;
        # client_max_body_size 10;
		upload_dir test/upload;
		auto_index true;
    }

    location /cgi-bin {
        root ./test;
        auto_index true;
        methods GET POST DELETE;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}
