server {
    listen 8080;
    host localhost;
    root .;
    index Makefile;

    location / {
        root .;
        methods GET;
    }

    location /src {
        root .;
        methods GET;
    }

    location /inc {
        root .;
        methods GET;
    }

    location /configs {
        root .;
        methods GET;
    }
}

